### ISSUE TITLE
Python 3: cPickle renamed to pickle (PEP3108)

### ISSUE THREAD

**Issue by hseg** [ssb22/lexconvert#5]
Hi, I'm packaging this for AUR, and I noticed the code unconditionally imports `cPickle`. This has been [deprecated for a decade and a half now](https://peps.python.org/pep-3108/) -- please at least gate the import behind a test for Python 2.7 (which, considering it's EOL for three years already, you may want to reconsider supporting anyway).
To my untrained eye, since the APIs are identical, it seems the only diff that's necessary is
```diff
diff --git a/lexconvert.py b/lexconvert.py
index af4dca5..3884ca7 100644
--- a/lexconvert.py
+++ b/lexconvert.py
@@ -3566,7 +3566,8 @@ class MacBritish_System_Lexicon(object):
             err = os.system("sudo touch \""+lexFile+"\" ; sudo chown "+str(os.getuid())+" \""+lexFile+"\"")
             assert not err, "Error creating lexdir"
         compat_err = "\nThis probably means your Mac has a new version of the voice that is no longer compatible with this system-lexicon patch."
-        import cPickle
+        try: import pickle as cPickle
+        except ImportError: import cPickle # pre-PEP 3108 (i.e. Python <3.0)^M
         if os.path.exists(lexFile) and os.stat(lexFile).st_size: self.wordIndexStart,self.wordIndexEnd,self.phIndexStart,self.phIndexEnd = cPickle.Unpickler(open(lexFile)).load()
         else:
             f = open(self.filename)
```
(or alternatively, put the renaming at the `cPickle` import and rename the use sites as well)

**Comment by ssb22** [comment]
Thanks, and thanks for your efforts to package this.

As far as Arch is concerned, you can completely ignore this part of the code, which runs only on MacOS 10.7 (an old system which has only Python 2) for handling the `mac-uk` output.  As I haven't yet had the opportunity to make this work on a more recent Mac, I didn't pay much attention to the class `MacBritish_System_Lexicon` when adding Python 3 support.  It would indeed be nice if at some point I could get this class to work on a more recent Mac and in Python 3, but currently it is the one part of lexconvert that is still stuck in the past.  There might be an argument for dropping it altogether, but I haven't done so, mainly because I haven't given up hope on one day being able to make it work on a more recent Mac, plus I do still sometimes use it on our old Mac Mini bought in 2012.

If some automatic checker tool is flagging up this import as a problem then we can of course gate it, but the surrounding code has other issues and is basically not supposed to be called at all except on an old Mac.  And there are checks in place that will refuse to run it if someone asks for it on another system.

Thanks again.

**Comment by hseg** [comment]
On Tue, Dec 19, 2023 at 07:47:49AM -0800, Silas S. Brown wrote:
> Thanks, and thanks for your efforts to package this.
> 
> As far as Arch is concerned, you can completely ignore this part of the code, which runs only on MacOS 10.7 (an old system which has only Python 2) for handling the `mac-uk` output.  As I haven't yet had the opportunity to make this work on a more recent Mac, I didn't pay much attention to the class `MacBritish_System_Lexicon` when adding Python 3 support.  It would indeed be nice if at some point I could get this class to work on a more recent Mac and in Python 3, but currently it is the one part of lexconvert that is still stuck in the past.  There might be an argument for dropping it altogether, but I haven't done so, mainly because I haven't given up hope on one day being able to make it work on a more recent Mac, plus I do still sometimes use it on our old Mac Mini bought in 2012.
> 
> If some automatic checker tool is flagging up this import as a problem then we can of course gate it, but the surrounding code has other issues and is basically not supposed to be called at all except on an old Mac.  And there are checks in place that will refuse to run it if someone asks for it on another system.
> 
Ah, hadn't noticed those checks. Yeah, only caught the import due to `namcap`
flagging it as a missing dependency (it also complained about the import of
commands.getoutput, but that was clearly signposted as a Python 2 fallback).
The code is sufficiently hard to read that I had missed the sys.version_info
assertions. Browsing the code a bit, I see enough occurrences of these
assertions that I feel comfortable trusting your statement that the checks cover
all entry points into MacBritish_System_Lexicon.
Thank you so much for your work on this! I especially use the IPA-espeak
conversions, though I'm sufficiently dissatisfied with espeak's pronunciation
that I might eventually change engines (or learn to use espeak better).
