### ISSUE TITLE
Issues with converting unicode-ipa (and other related formats), specifically with U+0061 'a'

### ISSUE THREAD

**Issue by RonBOakes** [ssb22/lexconvert#6]
According to the IPA charts and the Wikipedia reference on IPA, UTF representations, U+0061 should represent an open-front unrounded vowel.  When testing the current (as of 2024-02-08) version of lexconvert using the IPA representation of a couple of words from a constructed language and converting them into X-SAMPA, I saw the following results:

```
PS C:\Users\ron\source\repos\lexconvert> py lexconvert.py --phones2phones 'unicode-ipa' 'x-sampa' mipuθa hahao̯koxou̯
mipu:T{ h{h{@Uk@Ux@Uu:
```

Looking at the X-SAMPA reference, it shows that the { character represents the **near-open front unrounded vowel**.  This is the equivalent IPA character U+00E6 (æ).

Further testing showed that it could be reproduced in other cases of converting from unicode-ipa, but, perhaps, not all cases:

```
PS C:\Users\ron\source\repos\lexconvert> py lexconvert.py --phones2phones 'unicode-ipa' 'names' mipuθa hahao̯koxou̯
m e_as_in_eat p var2_oo_as_in_food th_as_in_think a_as_in_apple h a_as_in_apple h a_as_in_apple var1_o_as_in_go k var1_o_as_in_go opt_scottish_loch var1_o_as_in_go var2_oo_as_in_food
PS C:\Users\ron\source\repos\lexconvert> py lexconvert.py --phones2phones 'unicode-ipa' 'vocaloid' mipuθa hahao̯koxou̯
m i: p u: T { h { h { @U k @U x @U u:
PS C:\Users\ron\source\repos\lexconvert> py lexconvert.py --phones2phones 'unicode-ipa' 'unicode-rough' mipuθa hahao̯koxou̯
meepoothæ hæhæokoxooo
```

The first example, using 'names' as the output format, shows that it might be right (I'd say that at least with most U.S. American accents, the "a" at the start of "apple" is an open front unrounded vowel).  But the examples for vocaloid and even unicode-rough show the same issue as X-SAMPA.  I am not familiar with any of the other formats to the level to check with them.

**Comment by ssb22** [comment]
This is correct: lexconvert does not distinguish between "a" and "æ" when converting from Unicode-IPA.  Lexconvert also assumes that ʃ = ʧ and ɝ = ɜː and ʒ = ʤ and ɹ = r and ɔː = ɔ.

I am British, and most of the speech synths I convert between are British (eSpeak, Festival, etc), and British English does not have the "a" vs "æ" difference that American English has.  Basically I handled any extra American phonemes I didn't understand by mapping them onto their nearest British equivalents.  This can lose information if you try to convert from one American format to another.  And I'm afraid Lexconvert was never meant to be usable as a general phoneme converter for constructed languages: that's why I specifically said "English" in the description, as it works well enough for English words (at least as far as I can tell) but I don't necessarily know the subtleties of all the languages that aren't English.

The way to fix it for your particular use case is to create a `variant()` under `a_as_in_apple` in `Phonemes()`, and map this variant name to `a` in Unicode and to whatever the SAMPA equivalent is (we have to look that up).  The mapping can then be preserved when converting between Unicode and Sampa, while still approximating as "æ" for formats where we don't know the exact conversion (or where it doesn't exist, such as British speech synths).

Ideally I would like to create variants for all the American phonemes that don't have British equivalents, and check these have direct mappings in the American-capable voices like Sampa, but I haven't really trusted myself to be able to do this because it's too hard to stop my brain from automatically translating every English phoneme I hear into British.  If you're able to help with some of the mappings that would be great :)

**Comment by ssb22** [comment]
so IPA "a" maps to SAMPA "a" but this is not guaranteed to be supported by English voices, so we'd better not put in that mapping without either extensive testing or making it a variant dictionary with a caution

**Comment by ssb22** [comment]
Hi, please try version 0.4 and use `x-sampa-strict` instead of `x-sampa` (I wasn't sure if all voices support the difference so I put it in as a variant format just in case)
